name: CI
on:
  - push
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        platform:
          - Linux
          - macOS
          - Windows
        go-version:
          - '1.21'
          - '1.22'
          - '1.23'
        architecture:
          - amd64
          - arm64
        include:
          - platform: Linux
            os: ubuntu-latest
          - platform: Linux
            os: ubuntu-24.04-arm
            architecture: arm64
          - platform: macOS
            os: macos-latest
          - platform: macOS
            os: macos-13
            architecture: amd64
          - platform: Windows
            os: windows-latest
        exclude:
          - platform: Windows
            architecture: arm64
      fail-fast: false
    name: Go ${{ matrix.go-version }} (${{ matrix.architecture }}) on ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
      - name: Test
        run: go test -v -race -coverprofile coverage.txt ./...
      - name: Vet
        run: go vet ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: GO
          fail_ci_if_error: true
          flags: ${{ matrix.platform }}
        env:
          GO: ${{ matrix.go-version }}
