name: CI
on:
  - push
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        platform:
          - Linux
          - macOS
          - Windows
        go-version:
          - '1.19'
          - '1.20'
          - '1.21'
        include:
          - platform: Linux
            os: ubuntu-latest
          - platform: macOS
            os: macos-latest
          - platform: Windows
            os: windows-latest
      fail-fast: false
    name: Go ${{ matrix.go-version }} on ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
      - name: Test
        run: go test -v -race -coverprofile coverage.txt ./...
      - name: Vet
        run: go vet ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: ${{ matrix.platform }}
          env_vars: GO
        env:
          GO: ${{ matrix.go-version }}
